name: TASKFLOW CI

on:
  push:
    branches: 
      - main
      - test
      
  pull_request:
    branches: 
      - main
      
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: setup node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm
#####################
# Backend
    - name: Install Backend Dependencies
      working-directory: backend
      run: npm ci

#####################
# Frontendf
    - name: Install Frontend Dependencies
      working-directory: frontend
      run: npm ci

    - name: Build React App
      working-directory: frontend
      env:
        CI: false
      run: npm run build

#####################
# Docker Build
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Backend Docker Image
      run: |
        docker build \
        -t taskflow-backend:latest \
        ./backend
    - name: Build Frontend Docker Image
      run: |
        docker build \
        -t taskflow-frontend:latest \
        ./frontend
#####################
# Docker Compose Validation

    - name: Validate Docker Compose
      run: docker compose config
    
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test
